default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username:
  password:

development:
  <<: *default
  host: localhost
  database: peep_development

test:
  <<: *default
  database: peep_test

production:
  <<: *default
  database: peep_production
